language: node_js
node_js:
  - "stable"

sudo: false

before_script:
  cd server

script:
  npm test

after_success:
 — |
 curl -H “Content-Type: application/json” — data ‘{“build”: true}’ -X POST POST https://registry.hub.docker.com/u/bluecitylights/huecontrol/trigger/2fbc51db-6c39-4f7a-b8c2-72a38287a414/

