language: node_js
node_js:
  - "stable"

sudo: required

before_script:
  cd server

script:
  npm test
  
services:
  - docker

before install:
  - docker build -t bluecitylights\hueControl .


after_success:
  - if [ "$TRAVIS_BRANCH" == "seperate-server-folder" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi