language: node_js

sudo: required

before_install:
  cd server

install:
  npm install
  npm run build
  npm prune prune --production
services:
  - docker

before install:
  - docker build -t bluecitylights\hueControl .
